### ISSUE TITLE
Support ExternalAid link in QuestionConstruct

### ISSUE THREAD

**Issue by hildeorten** [DASISH/qddt-client#166] opened 2016-09-27 08:47 UTC
@StigNorland 
Add External aid to QuestionConstruct. 
This is a description and link to the External Aid (for example a showcard) using the Other Material structure.

See #109

**Comment by StigNorland** [comment] 2016-09-28 07:34
no need for this issue as it is a duplicate of #109

**Closed as completed by StigNorland** 2016-09-28 07:34 UTC
